version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: LoadForge_BD
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: LoadForge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
  rust:
    build: .
    container_name: Loadforge_API
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:123456789@postgres:5432/LoadForge
    mem_limit: 512m
    cpus: 0.5